working live_shots

diff --git a/scripts/lib/manage_docker b/scripts/lib/manage_docker
--- a/scripts/lib/manage_docker
+++ b/scripts/lib/manage_docker
@@ -16,4 +16,11 @@ start_docker() {
 stop_docker() {
     echo "Stopping docker compose"
     docker compose -f "${COMPOSE_FILE}" down -v
+    sleep 2
+    is_running=$(docker compose -f "${COMPOSE_FILE}" ps --all --filter status=running --quiet | wc -l)
+    if [[ ${is_running} -eq 0 ]]; then
+        echo "Docker compose stopped successfully"
+    else
+        echo "Failed to stop docker compose" >&2
+    fi
 }
